// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WatchlistApi.Data;

#nullable disable

namespace WatchlistApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720004622_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("WatchlistApi.Models.HistorialVistoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistorialVistos");
                });

            modelBuilder.Entity("WatchlistApi.Models.LibroItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CapituloActual")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CapituloFin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapituloInicio")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("TEXT");

                    b.Property<string>("PortadaUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LibroItems");
                });

            modelBuilder.Entity("WatchlistApi.Models.WatchlistItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiaEmision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnEmision")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodioFin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodioInicio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodiosVistos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("TEXT");

                    b.Property<string>("PortadaUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Visto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WatchlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
